### PR TITLE
Py37

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by nicoddemus** [comment]
I believe this package can be made `noarch` @ocefpaf

**Comment by nicoddemus** [comment]
We can remove the ` # [not win]` from the test command because we know it will only run on Windows anyway. 😁

**Comment by ocefpaf** [comment]
I'm never really sure if the plugin entrypoint in https://github.com/pytest-dev/pytest-forked/blob/master/setup.py#L15-L19 will play nice with `noarch`. I haven't test it but "regular" entrypoints only work when properly declared in the recipe and the plugin version, like that, is never declared.

@msarahan may know more.

Meanwhile let's keep this as-is until I can perform some tests and confirm that it is safe to make it `noarch`. (The answer may force is to revert or fix some other plugins too.)

**Comment by nicoddemus** [comment]
> I'm never really sure if the plugin entrypoint in https://github.com/pytest-dev/pytest-forked/blob/master/setup.py#L15-L19 will play nice with noarch

I think they do, because a lot of `noarch` pytest plugins don't declare the entry point at all and seem to work fine. Just a few examples:

* https://github.com/conda-forge/pytest-html-feedstock/blob/master/recipe/meta.yaml
* https://github.com/conda-forge/pytest-variables-feedstock/blob/master/recipe/meta.yaml
* https://github.com/conda-forge/pytest-metadata-feedstock/blob/master/recipe/meta.yaml

> Meanwhile let's keep this as-is until I can perform some tests and confirm that it is safe to make it noarch

Sure, sounds good!

**Comment by ocefpaf** [comment]
> and seem to work fine

Did you test any of those on Windows or macOS? If so I guess we can make this one `noarch` too.

**Comment by nicoddemus** [comment]
> Did you test any of those on Windows or macOS? If so I guess we can make this one noarch too.

On Windows definitely, but not on macOS. 😁

**Comment by ocefpaf** [comment]
> On Windows definitely, but not on macOS. 😁 

Good enough for me :smile: 


@conda-forge-admin, please add noarch: python

**Comment by nicoddemus** [comment]
:tada:

**Comment by nicoddemus** [comment]
(@ocefpaf, just so you know we run most of our tests in both Windows and Linux here at ESSS 😁)

**Comment by ocefpaf** [comment]
Glad to know. That means everything you pull from `conda-forge` is battle-tested on Windows :tada:

**Comment by nicoddemus** [comment]
Yep, that's generally the case. 😁

**Pull request merged**
